#配置数据库信息
spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    #更换数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.dadaibiao.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
